name: "Create user request"
description: "Submit a request to create user in our cluster"
labels: ["user admin"]
assignees: "sunhaocuhk"
body:
    -   type: textarea
        id: repro-steps
        attributes:
            label: Who are you?
            description: Tell us your name and school email addr.
            placeholder: |
                My name is Zhang Ming,
                I am student from course ABC123, my email addr is xxx@link.cuhk.edu.cn
        validations:
            required: true
    -   type: textarea
        id: expected-behaviour
        attributes:
            label: Why you want to use this cluster?
            description: Pls write one sentense
        validations:
            required: true
            
    -   type: textarea
        id: actual-behaviour
        attributes:
            label: Preferred username
            description: What's the preferred username you wish to use in the cluster? (at least two)
            placeholder: |
                1. zm
                2. zhangm
        validations:
            required: true

    -   type: input
        id: date
        attributes:
            label: until when do you plan to use the server? (2025-12-31)
        validations:
            required: true
   
